# Рейтинги отелей из канала @egypthotelz
# Формат: "ключевое слово в нижнем регистре": рейтинг (float)

HOTEL_RATINGS = {
    "barcelo tiran sharm":       7.9,
    "barceló tiran sharm":       7.9,
    "pickalbatros luxury suites":9.5,
    "jaz neo naama bay":         8.6,
    "jaz neo sharks bay":        8.4,
    "hawaii riviera":            7.6,
    "minamark":                  7.6,
    "regency plaza":             7.8,
    "panorama naama":            7.8,
    "amphoras aqua":             7.8,
    "empire beach":              7.8,
    "le pacha":                  7.8,
    "oonas dive":                7.9,
    "jaz aquaviva":              7.9,
    "amphoras blu":              7.9,
    "naama blue":                8.0,
    "marlin inn azur":           8.1,
    "tropitel dahab":            8.1,
    "shores amphoras":           8.1,
    "sharm holiday":             8.2,
    "il mercato":                8.2,
    "steigenberger aqua":        8.2,
    "jaz sharks bay":            8.3,
    "giftun azur":               8.3,
    "domina coral bay":          8.4,
    "cleopatra luxury":          8.4,
    "reef oasis blue bay":       8.4,
    "alf leila":                 8.4,
    "albatros citadel":          8.5,
    "coral sea holiday":         8.5,
    "tropitel sahl":             8.6,
    "hilton sharks bay":         8.6,
    "concorde el salam":         8.6,
    "ali baba palace":           8.6,
    "mirage bay":                8.7,
    "beach albatros sharm":      8.7,
    "coral sea waterworld":      8.7,
    "camel dive":                8.7,
    "meraki resort":             8.7,
    "sentido reef":              8.7,
    "charmillion":               8.7,
    "hilton hurghada plaza":     8.7,
    "desert rose":               8.7,
    "swissôtel sharm":           8.7,
    "swissotel sharm":           8.7,
    "steigenberger golf":        8.7,
    "hilton marsa alam":         8.8,
    "titanic resort":            8.8,
    "jaz sharm dreams":          8.8,
    "albatros palace":           8.8,
    "pickalbatros jungle":       8.8,
    "pickalbatros white beach":  8.8,
    "reef oasis beach":          8.8,
    "sultan gardens resort":     8.8,
    "grand rotana":              8.9,
    "hyatt regency sharm":       8.9,
    "titanic beach spa":         8.9,
    "pickalbatros water valley": 8.9,
    "pickalbatros aqua park":    8.9,
    "monte carlo sharm":         8.9,
    "jaz aquamarine":            8.9,
    "jaz fanara":                9.0,
    "jaz mirabel":               9.0,
    "pickalbatros laguna vista": 9.0,
    "titanic palace":            9.0,
    "rixos premium seagate":     9.0,
    "sunrise holidays resort":   9.0,
    "sunrise royal makadi":      9.0,
    "baron palms":               9.0,
    "baron resort sharm":        9.1,
    "sultan gardens":            9.1,
    "savoy sharm":               9.1,
    "savoy royal":               9.1,
    "titanic royal":             9.1,
    "steigenberger aldau":       9.1,
    "sunrise diamond":           9.1,
    "jaz belvedere":             9.2,
    "premier le reve":           9.2,
    "sunrise arabian beach":     9.2,
    "rixos premium magawish":    9.2,
    "rixos radamis":             9.2,
    "steigenberger alcazar":     9.2,
    "sunrise montemare":         9.2,
    "sunrise alora":             9.2,
    "baron palace sahl":         9.2,
    "serry beach":               9.2,
    "jaz makadi gardens":        9.2,
    "jaz makadi star":           9.3,
    "steigenberger pure life":   9.3,
    "rixos sharm adults":        9.3,
    "pickalbatros royal moderna":9.3,
    "pickalbatros royal grand":  9.3,
    "four seasons":              9.3,
    "coral sea imperial":        9.4,
    "jaz soma beach":            9.4,
    "titanic deluxe sharm":      9.4,
    "oberoi beach":              9.6,
}


def get_rating(hotel_name: str):
    """Возвращает (рейтинг, None) или (None, None)."""
    name = hotel_name.lower()
    for key, rating in HOTEL_RATINGS.items():
        if key in name:
            return rating, None
    name_words = set(name.split())
    best_match = None
    best_count = 1
    for key, rating in HOTEL_RATINGS.items():
        key_words = set(key.split())
        common = len(key_words & name_words)
        if common > best_count:
            best_count = common
            best_match = (rating, None)
    return best_match if best_match else (None, None)
